error: correctly initialize error code per-thread
* scew/xerror.c (scew_error_set_last_error_): if pthread_getspecific
  returns NULL we need to allocate a new error code for this thread.

  Fixes http://savannah.nongnu.org/bugs/?41001